show databases;
use sakila;
SELECT version(), current_date();
 SELECT SIN(PI()/4), (4+1)*5;
  SELECT VERSION(); SELECT NOW();
  
  
CREATE TABLE EMPLOYEE (Fname VARCHAR(15) NOT NULL,
Minit CHAR,
Lname VARCHAR(15) NOT NULL,
Ssn CHAR(9) NOT NULL PRIMARY KEY,
Bdate DATE NOT NULL,
Address VARCHAR(30),
Sex CHAR,
Salary DECIMAL(10,2),
Super_ssn CHAR(9) REFERENCES EMPLOYEE(Ssn),
Dno INT REFERENCES DEPARTMENT(Dnumber));


CREATE TABLE DEPARTMENT (

Dname VARCHAR(15) NOT NULL UNIQUE,
Dnumber INT NOT NULL PRIMARY KEY,
Mgr_ssn CHAR(9) NOT NULL,
Mgr_start_date DATE


);

CREATE TABLE DEPT_LOCATIONS (

Dnumber INT NOT NULL PRIMARY KEY REFERENCES DEPARTMENT(Dnumber),
Dlocation VARCHAR(15) NOT NULL PRIMARY KEY

);



CREATE TABLE PROJECT (

Pname VARCHAR(15) NOT NULL UNIQUE,
Pnumber INT NOT NULL PRIMARY KEY,
Plocation VARCHAR(15) NOT NULL,
Dnum INT REFERENCES DEPARTMENT(Dnumber)


);


CREATE TABLE WORKS_ON (

Essn CHAR(9) NOT NULL PRIMARY KEY REFERENCES EMPLOYEE(Ssn),
Pno INT NOT NULL PRIMARY KEY REFERENCES PROJECT(Pnumber),
Hours DECIMAL(3,1)


);



CREATE TABLE DEPENDANT (

Essn CHAR(9) NOT NULL PRIMARY KEY REFERENCES EMPLOYEE(Ssn),
Dependent_name VARCHAR(15) NOT NULL PRIMARY KEY,
Sex CHAR,
Bdate DATE,
Relationship VARCHAR(8)


);





INSERT INTO EMPLOYEE VALUES
('a','a','a','my_ssn','1971-12-12',NULL, NULL, NULL, 'my_sssn', 12)
;
